permissions:
  - 'access taxonomy overview'
  - 'administer permissions'
  - 'use text format full_html'
  - 'access taxonomy overview'
  - 'administer permissions'
  - 'create terms in constituency'
  - 'create terms in political_group'
  - 'create terms in role_type'
  - 'create terms in tag'
  - 'delete terms in constituency'
  - 'delete terms in political_group'
  - 'delete terms in role_type'
  - 'delete terms in tag'
  - 'edit terms in constituency'
  - 'edit terms in political_group'
  - 'edit terms in role_type'
  - 'edit terms in tag'
  - 'rabbit hole bypass taxonomy_term'
  - 'use text format full_html'
