permissions:
  - 'access taxonomy overview'
  - 'create terms in constituency'
  - 'create terms in political_group'
  - 'create terms in role_type'
  - 'delete terms in constituency'
  - 'delete terms in political_group'
  - 'delete terms in role_type'
  - 'edit terms in constituency'
  - 'edit terms in political_group'
  - 'edit terms in role_type'
  - 'rabbit hole bypass taxonomy_term'
